<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Degrees [
<!ELEMENT Degrees (degree+)>
<!ELEMENT degree (name, center)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT center (#PCDATA)>
]>

<Degrees>
    <degree>
        <name>40ºC</name>
        <center>Sevilla</center>
    </degree>
    <degree>
        <name>38ºC</name>
        <center>New York</center>
    </degree>
    <degree>
        <name>29ºC</name>
        <center>Paris</center>
    </degree>
    <degree>
        <name>0ºC</name>
        <center>Orlando</center>
    </degree>
    <degree>
        <name>19ºC</name>
        <center>Chicago</center>
    </degree>
    <degree>
        <name>-5ºC</name>
        <center>San Petesburgo</center>
    </degree>
</Degrees>
